#!/bin/bash

PROJECT="$1"
PROJECT_PATH_URL=`curl -s "https://github.com/search?utf8=%E2%9C%93&q=$PROJECT&repo=&langOverride=&start_value=1&type=Repositories&language=" | \
             xmllint --xmlout --html --xpath "string(//div[@class='result'][1]/h2/a/@href)" - 2>/dev/null`
PROJECT_URL="https://github.com$PROJECT_PATH_URL"

ISSUES_PAGE=`curl -s "$PROJECT_URL/issues"`
NB_OPEN_ISSUES=`echo $ISSUES_PAGE \
  | xmllint --xmlout --html --xpath "//li[@data-filter='open']/a/text()" - 2>/dev/null \
  | sed 's/[^0-9]//g'`
NB_CLOSED_ISSUES=`echo $ISSUES_PAGE \
  | xmllint --xmlout --html --xpath "//li[@data-filter='closed']/a/text()" - 2>/dev/null \
  | sed 's/[^0-9]//g'`
NB_ISSUES=`expr $NB_OPEN_ISSUES + $NB_CLOSED_ISSUES`

PULLS_PAGE=`curl -s "$PROJECT_URL/pulls"`
NB_PULLS=`echo $PULLS_PAGE \
  | xmllint --xmlout --html --xpath "//a[@highlight='repo_pulls']/span/text()" - 2>/dev/null`  

NB_WATCHERS=`echo $PULLS_PAGE \
  | xmllint --xmlout --html --xpath "//li[@class='watchers ']/a/text()" - 2>/dev/null \
  | sed 's/[^0-9]//g'`
NB_FORKS=`echo $PULLS_PAGE \
  | xmllint --xmlout --html --xpath "//li[@class='forks']/a/text()" - 2>/dev/null \
  | sed 's/[^0-9]//g'`

CODE_PAGE=`curl -s "$PROJECT_URL"`
NB_TAGS=`echo $CODE_PAGE \
  | xmllint --xmlout --html --xpath "//a[@highlight='repo_tags']/span/text()" - 2>/dev/null`  

JSON_REPOS=`curl -s https://api.github.com/repos$PROJECT_PATH_URL`
DAYS_FROM_START=`echo $JSON_REPOS | php -r "echo floor((time() - strtotime(json_decode(file_get_contents('php://stdin'))->created_at))/60/60/24);"`
NO_ACTIVITY_DAYS=`echo $JSON_REPOS | php -r "echo floor((time() - strtotime(json_decode(file_get_contents('php://stdin'))->updated_at))/60/60/24);"`

POPULARITY_SCORE=`wcalc -q -P0 "($NB_ISSUES * 4.58438 * 1 + $NB_PULLS * 150.126 * 3 + $NB_WATCHERS * 1 * 1 + $NB_FORKS * 8.4994 * 2 + $NB_TAGS * 102.734 * 2)/17.9988"`

echo "$PROJECT project popularity score is $POPULARITY_SCORE"
echo "----"
echo "score = $POPULARITY_SCORE"
echo "pulls = $NB_PULLS"
echo "forks = $NB_FORKS"
echo "tags = $NB_TAGS"
echo "issues = $NB_ISSUES"
echo "open_issues = $NB_OPEN_ISSUES"
echo "closed_issues = $NB_CLOSED_ISSUES"
echo "watchers = $NB_WATCHERS"
echo "days_from_start = $DAYS_FROM_START"
echo "no_activity_days = $NO_ACTIVITY_DAYS"
echo "project_url = $PROJECT_URL"